# Generated by Django 2.2 on 2022-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
